"""Verbatim port of ``src/mocks/mockReports.ts``.

The report bodies are copied character for character. The frontend renders them
as Markdown and the snapshot tests assert on them, so do not reflow or reword.
"""

from __future__ import annotations

from datetime import UTC, datetime

VODAFONE_REPORT = """# Strategic Account Intelligence: Vodafone Group Plc

**Target Account:** Vodafone Group Plc  
**Account Identifier:** ACC-VOD-8821  
**Target Geography:** United Kingdom & Western Europe  
**Primary Industry:** Telecommunications, Cloud & Digital Services  

---

## 1. Executive Summary
Vodafone Group Plc is executing a pan-European digital infrastructure refresh aimed at supporting standalone 5G backhaul, enterprise SD-WAN connectivity, and hybrid cloud interconnect. Colt's ultra-low latency IQ Network and On-Demand bandwidth platforms directly align with Vodafone's strategic mandate to reduce cross-border transit latency while consolidating telecom carrier partners across the UK, Germany, and Southern Europe.

## 2. Key Business & Strategic Signals
- **5G Core and Fiber Densification:** Expanding 5G mid-band spectrum coverage with high-capacity 100G/400G optical routes between London, Frankfurt, and Amsterdam.
- **Enterprise Cloud On-Ramp Growth:** Strategic joint ventures with AWS and Microsoft Azure creating surging demand for carrier-grade Data Center Interconnect (DCI).
- **Vendor Rationalization Initiative:** Vodafone Procurement is actively seeking unified SLAs and standardized master contracts across multinational footprints.

## 3. Financial & Operational Highlights
- **Annual Group Revenue:** €36.7 Billion
- **Business/Enterprise Sector Growth:** +5.2% YoY (driven by IoT & Cloud Managed Services)
- **Infrastructure Investment Allocation:** €7.4 Billion focused on optical networks and digital core architecture.

## 4. High-Value Colt Solutions & Differentiators
- **Colt Wave & Spectrum Services:** Dedicated 400G/800G wavelengths across Tier-1 financial and cloud corridors with deterministic sub-millisecond latencies.
- **Colt On-Demand SDN Portal:** Self-service real-time bandwidth provisioning allowing Vodafone wholesale teams to scale throughput dynamically.
- **Single Master Services Agreement:** Unified pan-European billing, multi-currency support, and single-pane-of-glass operations.

## 5. Recommended Sales Action Plan
1. **Initiate Technical Briefing:** Coordinate with Colt Solutions Architects to present benchmark latency telemetry on London-Frankfurt-Zurich corridors.
2. **Deliver Commercial Proposal:** Present customized Dark Fiber & Protected Optical Wave package for primary aggregation hubs.
3. **Executive Sponsor Alignment:** Arrange briefing between Colt VP of Wholesale and Vodafone Head of Network Procurement."""

DEUTSCHE_TELEKOM_REPORT = """# Strategic Account Intelligence: Deutsche Telekom AG

**Target Account:** Deutsche Telekom AG  
**Account Identifier:** ACC-DT-4412  
**Target Geography:** Germany & Central Europe  
**Primary Industry:** Enterprise ICT & Optical Telecommunications  

---

## 1. Executive Summary
Deutsche Telekom AG (T-Systems / Global Carrier division) is expanding its pan-European secure edge network and sovereign cloud offerings. Colt represents an ideal infrastructure partner to extend T-Systems' enterprise reach into key metro areas across the UK, France, and Southern Europe where Colt owns dense on-net fiber footprints.

## 2. Strategic Focus Areas
- **Sovereign Cloud Connectivity:** Integrating Gaia-X compliant data center nodes across Frankfurt, Paris, and Amsterdam.
- **Metro Fiber Reach:** Expanding high-density enterprise building connections without high civil engineering capex.
- **Automated Carrier Interconnect:** Implementing MEF LSO APIs for automated quote-to-order carrier services.

## 3. Colt Positioning & Next Steps
- Leverage Colt's on-net connection to over 32,000 enterprise buildings and 1,000+ data centers worldwide.
- Propose joint API integration for automated cross-carrier Ethernet service activation."""

_MONTHS = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)


def _en_gb_date(moment: datetime | None = None) -> str:
    """Match JS ``toLocaleDateString('en-GB', {day:'numeric',month:'long',year:'numeric'})``."""
    moment = moment or datetime.now(UTC)
    return f"{moment.day} {_MONTHS[moment.month - 1]} {moment.year}"


def generate_custom_report(company_name: str, account_id: str) -> str:
    date_str = _en_gb_date()
    return f"""# Comprehensive Account Intelligence: {company_name}

**Target Account:** {company_name}  
**Account Identifier:** {account_id}  
**Date Generated:** {date_str}  
**Generated By:** Colt Sales Agent (Gemini 2.5 Pro)  

---

## 1. Executive Summary
{company_name} is actively pursuing cloud transformation, distributed edge compute connectivity, and cross-border networking enhancements across its primary corporate facilities. Colt's high-speed optical IQ Network, cloud direct on-ramps (AWS, Azure, Google Cloud), and On-Demand bandwidth SDN platform present significant alignment with {company_name}'s target operational roadmap.

## 2. Core Business Strategy & Market Signals
- **Digital Infrastructure Modernization:** Upgrading legacy enterprise WAN to secure, software-defined high-availability circuits.
- **Hyperscaler Cloud Migration:** Multi-cloud data aggregation requiring deterministic low-latency carrier connections with stringent SLAs.
- **Operational Cost Optimization:** Consolidating regional telecom and colocation providers under single-point pan-European frameworks.

## 3. High-Value Colt Synergy Points
- **Colt Wave & Metro Services:** Dedicated 100G/400G optical wavelengths connecting major data center facilities and corporate headquarters.
- **Colt On-Demand:** Self-service real-time bandwidth scaling via intuitive portal and REST APIs.
- **Unified Account Management:** Colt provides a single pan-European contractual agreement with multi-currency billing and 24/7 dedicated enterprise support.

## 4. Recommended Engagement Roadmap
1. **Initial Stakeholder Discovery:** Schedule an introductory architectural alignment call with {company_name}'s Enterprise Infrastructure team.
2. **Technical Feasibility & Latency Assessment:** Present verified route latency metrics connecting primary office locations and data centers.
3. **Commercial Proposal:** Deliver a tailored multi-year Dark Fiber / Dedicated Wavelength pricing model."""
