import type { IncomingMessage, ServerResponse } from 'node:http';
import { mockDb } from './mockDb.ts';
import { readBody, sendJson } from './translationMockRouter.ts';


export async function handleSalesMock(
  pathname: string,
  method: string,
  req: IncomingMessage,
  res: ServerResponse,
): Promise<boolean> {
  if (pathname === '/api/sales/v1/research/jobs' && method === 'GET') {
    const jobs = mockDb.getSalesJobs();
    sendJson(res, 200, { jobs, total: jobs.length });
    return true;
  }

  if (pathname === '/api/sales/v1/research/initiate' && method === 'POST') {
    const raw = await readBody(req);
    try {
      const parsed = JSON.parse(raw) as { company_name?: string; account_id?: string };
      const companyName = parsed.company_name || 'Enterprise Target';
      const accountId = parsed.account_id || `ACC-${companyName.slice(0, 3).toUpperCase()}-101`;
      const result = mockDb.initiateSalesResearch(companyName, accountId);
      sendJson(res, 200, result);
    } catch {
      sendJson(res, 400, { error: { message: 'Invalid JSON payload' } });
    }
    return true;
  }

  const salesStatusMatch = pathname.match(/^\/api\/sales\/v1\/research\/status\/([^/]+)$/);
  if (salesStatusMatch && method === 'GET') {
    const jobId = salesStatusMatch[1];
    const status = mockDb.getSalesJobStatus(jobId);
    if (!status) {
      sendJson(res, 404, { error: { message: `Sales job ${jobId} not found` } });
    } else {
      sendJson(res, 200, status);
    }
    return true;
  }

  const salesResultMatch = pathname.match(/^\/api\/sales\/v1\/research\/result\/([^/]+)$/);
  if (salesResultMatch && method === 'GET') {
    const jobId = salesResultMatch[1];
    const result = mockDb.getSalesJobResult(jobId);
    if (!result) {
      sendJson(res, 404, { error: { message: `Sales result for ${jobId} not found` } });
    } else {
      sendJson(res, 200, result);
    }
    return true;
  }

  const salesDownloadMatch = pathname.match(/^\/api\/sales\/v1\/research\/download\/([^/]+)$/);
  if (salesDownloadMatch && method === 'GET') {
    const jobId = salesDownloadMatch[1];
    const result = mockDb.getSalesJobResult(jobId);
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="sales-research-${jobId}.md"`);
    res.end(result?.report_content || `# Sales Research Report (${jobId})\n\nGenerated by Colt AI Hub Sales Agent.`);
    return true;
  }

  const salesCancelMatch = pathname.match(/^\/api\/sales\/v1\/research\/([^/]+)$/);
  if (salesCancelMatch && method === 'DELETE') {
    const jobId = salesCancelMatch[1];
    mockDb.cancelSalesResearch(jobId);
    sendJson(res, 200, { message: `Sales research job ${jobId} cancelled.` });
    return true;
  }

  return false;
}
